// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod niri_shell {


pub enum ClientCommandOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ClientCommand<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ClientCommand<'a> {
  type Inner = ClientCommand<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ClientCommand<'a> {
  pub const VT_ACTION: ::flatbuffers::VOffsetT = 4;
  pub const VT_ARG_INT: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ClientCommand { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ClientCommandArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ClientCommand<'bldr>> {
    let mut builder = ClientCommandBuilder::new(_fbb);
    builder.add_arg_int(args.arg_int);
    if let Some(x) = args.action { builder.add_action(x); }
    builder.finish()
  }


  #[inline]
  pub fn action(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ClientCommand::VT_ACTION, None)}
  }
  #[inline]
  pub fn arg_int(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(ClientCommand::VT_ARG_INT, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for ClientCommand<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("action", Self::VT_ACTION, false)?
     .visit_field::<i32>("arg_int", Self::VT_ARG_INT, false)?
     .finish();
    Ok(())
  }
}
pub struct ClientCommandArgs<'a> {
    pub action: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub arg_int: i32,
}
impl<'a> Default for ClientCommandArgs<'a> {
  #[inline]
  fn default() -> Self {
    ClientCommandArgs {
      action: None,
      arg_int: 0,
    }
  }
}

pub struct ClientCommandBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ClientCommandBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_action(&mut self, action: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ClientCommand::VT_ACTION, action);
  }
  #[inline]
  pub fn add_arg_int(&mut self, arg_int: i32) {
    self.fbb_.push_slot::<i32>(ClientCommand::VT_ARG_INT, arg_int, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ClientCommandBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ClientCommandBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ClientCommand<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ClientCommand<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ClientCommand");
      ds.field("action", &self.action());
      ds.field("arg_int", &self.arg_int());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `ClientCommand`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_client_command_unchecked`.
pub fn root_as_client_command(buf: &[u8]) -> Result<ClientCommand<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<ClientCommand>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `ClientCommand` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_client_command_unchecked`.
pub fn size_prefixed_root_as_client_command(buf: &[u8]) -> Result<ClientCommand<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<ClientCommand>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `ClientCommand` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_client_command_unchecked`.
pub fn root_as_client_command_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ClientCommand<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<ClientCommand<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `ClientCommand` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_client_command_unchecked`.
pub fn size_prefixed_root_as_client_command_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ClientCommand<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<ClientCommand<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a ClientCommand and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `ClientCommand`.
pub unsafe fn root_as_client_command_unchecked(buf: &[u8]) -> ClientCommand<'_> {
  unsafe { ::flatbuffers::root_unchecked::<ClientCommand>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed ClientCommand and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `ClientCommand`.
pub unsafe fn size_prefixed_root_as_client_command_unchecked(buf: &[u8]) -> ClientCommand<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<ClientCommand>(buf) }
}
#[inline]
pub fn finish_client_command_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<ClientCommand<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_client_command_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<ClientCommand<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod NiriShell

