// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CLIENTCOMMAND_NIRISHELL_H_
#define FLATBUFFERS_GENERATED_CLIENTCOMMAND_NIRISHELL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace NiriShell {

struct ClientCommand;
struct ClientCommandBuilder;

struct ClientCommand FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientCommandBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACTION = 4,
    VT_ARG_INT = 6
  };
  const ::flatbuffers::String *action() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACTION);
  }
  int32_t arg_int() const {
    return GetField<int32_t>(VT_ARG_INT, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ACTION) &&
           verifier.VerifyString(action()) &&
           VerifyField<int32_t>(verifier, VT_ARG_INT, 4) &&
           verifier.EndTable();
  }
};

struct ClientCommandBuilder {
  typedef ClientCommand Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_action(::flatbuffers::Offset<::flatbuffers::String> action) {
    fbb_.AddOffset(ClientCommand::VT_ACTION, action);
  }
  void add_arg_int(int32_t arg_int) {
    fbb_.AddElement<int32_t>(ClientCommand::VT_ARG_INT, arg_int, 0);
  }
  explicit ClientCommandBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientCommand> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientCommand>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientCommand> CreateClientCommand(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> action = 0,
    int32_t arg_int = 0) {
  ClientCommandBuilder builder_(_fbb);
  builder_.add_arg_int(arg_int);
  builder_.add_action(action);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ClientCommand> CreateClientCommandDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *action = nullptr,
    int32_t arg_int = 0) {
  auto action__ = action ? _fbb.CreateString(action) : 0;
  return NiriShell::CreateClientCommand(
      _fbb,
      action__,
      arg_int);
}

inline const NiriShell::ClientCommand *GetClientCommand(const void *buf) {
  return ::flatbuffers::GetRoot<NiriShell::ClientCommand>(buf);
}

inline const NiriShell::ClientCommand *GetSizePrefixedClientCommand(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<NiriShell::ClientCommand>(buf);
}

template <bool B = false>
inline bool VerifyClientCommandBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<NiriShell::ClientCommand>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedClientCommandBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<NiriShell::ClientCommand>(nullptr);
}

inline void FinishClientCommandBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NiriShell::ClientCommand> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedClientCommandBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NiriShell::ClientCommand> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace NiriShell

#endif  // FLATBUFFERS_GENERATED_CLIENTCOMMAND_NIRISHELL_H_
