// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod niri_shell {


pub enum WorkspaceOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Workspace<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Workspace<'a> {
  type Inner = Workspace<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Workspace<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_NAME: ::flatbuffers::VOffsetT = 6;
  pub const VT_IS_ACTIVE: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Workspace { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args WorkspaceArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Workspace<'bldr>> {
    let mut builder = WorkspaceBuilder::new(_fbb);
    builder.add_id(args.id);
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_is_active(args.is_active);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Workspace::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Workspace::VT_NAME, None)}
  }
  #[inline]
  pub fn is_active(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Workspace::VT_IS_ACTIVE, Some(false)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Workspace<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("id", Self::VT_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<bool>("is_active", Self::VT_IS_ACTIVE, false)?
     .finish();
    Ok(())
  }
}
pub struct WorkspaceArgs<'a> {
    pub id: u64,
    pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub is_active: bool,
}
impl<'a> Default for WorkspaceArgs<'a> {
  #[inline]
  fn default() -> Self {
    WorkspaceArgs {
      id: 0,
      name: None,
      is_active: false,
    }
  }
}

pub struct WorkspaceBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> WorkspaceBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: u64) {
    self.fbb_.push_slot::<u64>(Workspace::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Workspace::VT_NAME, name);
  }
  #[inline]
  pub fn add_is_active(&mut self, is_active: bool) {
    self.fbb_.push_slot::<bool>(Workspace::VT_IS_ACTIVE, is_active, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> WorkspaceBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    WorkspaceBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Workspace<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Workspace<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Workspace");
      ds.field("id", &self.id());
      ds.field("name", &self.name());
      ds.field("is_active", &self.is_active());
      ds.finish()
  }
}
pub enum ShellStateOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ShellState<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ShellState<'a> {
  type Inner = ShellState<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ShellState<'a> {
  pub const VT_WORKSPACES: ::flatbuffers::VOffsetT = 4;
  pub const VT_BATTERY_PERCENT: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ShellState { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ShellStateArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ShellState<'bldr>> {
    let mut builder = ShellStateBuilder::new(_fbb);
    if let Some(x) = args.workspaces { builder.add_workspaces(x); }
    builder.add_battery_percent(args.battery_percent);
    builder.finish()
  }


  #[inline]
  pub fn workspaces(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Workspace<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Workspace>>>>(ShellState::VT_WORKSPACES, None)}
  }
  #[inline]
  pub fn battery_percent(&self) -> i8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i8>(ShellState::VT_BATTERY_PERCENT, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for ShellState<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Workspace>>>>("workspaces", Self::VT_WORKSPACES, false)?
     .visit_field::<i8>("battery_percent", Self::VT_BATTERY_PERCENT, false)?
     .finish();
    Ok(())
  }
}
pub struct ShellStateArgs<'a> {
    pub workspaces: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Workspace<'a>>>>>,
    pub battery_percent: i8,
}
impl<'a> Default for ShellStateArgs<'a> {
  #[inline]
  fn default() -> Self {
    ShellStateArgs {
      workspaces: None,
      battery_percent: 0,
    }
  }
}

pub struct ShellStateBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ShellStateBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_workspaces(&mut self, workspaces: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Workspace<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ShellState::VT_WORKSPACES, workspaces);
  }
  #[inline]
  pub fn add_battery_percent(&mut self, battery_percent: i8) {
    self.fbb_.push_slot::<i8>(ShellState::VT_BATTERY_PERCENT, battery_percent, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ShellStateBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ShellStateBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ShellState<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ShellState<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ShellState");
      ds.field("workspaces", &self.workspaces());
      ds.field("battery_percent", &self.battery_percent());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `ShellState`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_shell_state_unchecked`.
pub fn root_as_shell_state(buf: &[u8]) -> Result<ShellState<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<ShellState>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `ShellState` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_shell_state_unchecked`.
pub fn size_prefixed_root_as_shell_state(buf: &[u8]) -> Result<ShellState<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<ShellState>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `ShellState` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_shell_state_unchecked`.
pub fn root_as_shell_state_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ShellState<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<ShellState<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `ShellState` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_shell_state_unchecked`.
pub fn size_prefixed_root_as_shell_state_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ShellState<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<ShellState<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a ShellState and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `ShellState`.
pub unsafe fn root_as_shell_state_unchecked(buf: &[u8]) -> ShellState<'_> {
  unsafe { ::flatbuffers::root_unchecked::<ShellState>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed ShellState and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `ShellState`.
pub unsafe fn size_prefixed_root_as_shell_state_unchecked(buf: &[u8]) -> ShellState<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<ShellState>(buf) }
}
#[inline]
pub fn finish_shell_state_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<ShellState<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_shell_state_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<ShellState<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod NiriShell

