// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SHELLSTATE_NIRISHELL_H_
#define FLATBUFFERS_GENERATED_SHELLSTATE_NIRISHELL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace NiriShell {

struct Theme;
struct ThemeBuilder;

struct Workspace;
struct WorkspaceBuilder;

struct ShellState;
struct ShellStateBuilder;

struct Theme FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ThemeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BG_COLOR = 4,
    VT_FG_COLOR = 6,
    VT_ACCENT_COLOR = 8
  };
  const ::flatbuffers::String *bg_color() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BG_COLOR);
  }
  const ::flatbuffers::String *fg_color() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FG_COLOR);
  }
  const ::flatbuffers::String *accent_color() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACCENT_COLOR);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BG_COLOR) &&
           verifier.VerifyString(bg_color()) &&
           VerifyOffset(verifier, VT_FG_COLOR) &&
           verifier.VerifyString(fg_color()) &&
           VerifyOffset(verifier, VT_ACCENT_COLOR) &&
           verifier.VerifyString(accent_color()) &&
           verifier.EndTable();
  }
};

struct ThemeBuilder {
  typedef Theme Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_bg_color(::flatbuffers::Offset<::flatbuffers::String> bg_color) {
    fbb_.AddOffset(Theme::VT_BG_COLOR, bg_color);
  }
  void add_fg_color(::flatbuffers::Offset<::flatbuffers::String> fg_color) {
    fbb_.AddOffset(Theme::VT_FG_COLOR, fg_color);
  }
  void add_accent_color(::flatbuffers::Offset<::flatbuffers::String> accent_color) {
    fbb_.AddOffset(Theme::VT_ACCENT_COLOR, accent_color);
  }
  explicit ThemeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Theme> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Theme>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Theme> CreateTheme(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> bg_color = 0,
    ::flatbuffers::Offset<::flatbuffers::String> fg_color = 0,
    ::flatbuffers::Offset<::flatbuffers::String> accent_color = 0) {
  ThemeBuilder builder_(_fbb);
  builder_.add_accent_color(accent_color);
  builder_.add_fg_color(fg_color);
  builder_.add_bg_color(bg_color);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Theme> CreateThemeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *bg_color = nullptr,
    const char *fg_color = nullptr,
    const char *accent_color = nullptr) {
  auto bg_color__ = bg_color ? _fbb.CreateString(bg_color) : 0;
  auto fg_color__ = fg_color ? _fbb.CreateString(fg_color) : 0;
  auto accent_color__ = accent_color ? _fbb.CreateString(accent_color) : 0;
  return NiriShell::CreateTheme(
      _fbb,
      bg_color__,
      fg_color__,
      accent_color__);
}

struct Workspace FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WorkspaceBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_NAME = 6,
    VT_IS_ACTIVE = 8
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool is_active() const {
    return GetField<uint8_t>(VT_IS_ACTIVE, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID, 8) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint8_t>(verifier, VT_IS_ACTIVE, 1) &&
           verifier.EndTable();
  }
};

struct WorkspaceBuilder {
  typedef Workspace Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(Workspace::VT_ID, id, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Workspace::VT_NAME, name);
  }
  void add_is_active(bool is_active) {
    fbb_.AddElement<uint8_t>(Workspace::VT_IS_ACTIVE, static_cast<uint8_t>(is_active), 0);
  }
  explicit WorkspaceBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Workspace> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Workspace>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Workspace> CreateWorkspace(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    bool is_active = false) {
  WorkspaceBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_name(name);
  builder_.add_is_active(is_active);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Workspace> CreateWorkspaceDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    const char *name = nullptr,
    bool is_active = false) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return NiriShell::CreateWorkspace(
      _fbb,
      id,
      name__,
      is_active);
}

struct ShellState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ShellStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WORKSPACES = 4,
    VT_BATTERY_PERCENT = 6,
    VT_ACTIVE_WINDOW_TITLE = 8,
    VT_AUDIO_VOLUME = 10,
    VT_AUDIO_MUTED = 12,
    VT_NETWORK_NAME = 14,
    VT_TOGGLE_CC_SIGNAL = 16,
    VT_THEME = 18,
    VT_AVAILABLE_THEMES = 20
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<NiriShell::Workspace>> *workspaces() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<NiriShell::Workspace>> *>(VT_WORKSPACES);
  }
  int8_t battery_percent() const {
    return GetField<int8_t>(VT_BATTERY_PERCENT, 0);
  }
  const ::flatbuffers::String *active_window_title() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACTIVE_WINDOW_TITLE);
  }
  int8_t audio_volume() const {
    return GetField<int8_t>(VT_AUDIO_VOLUME, 0);
  }
  bool audio_muted() const {
    return GetField<uint8_t>(VT_AUDIO_MUTED, 0) != 0;
  }
  const ::flatbuffers::String *network_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NETWORK_NAME);
  }
  uint8_t toggle_cc_signal() const {
    return GetField<uint8_t>(VT_TOGGLE_CC_SIGNAL, 0);
  }
  const NiriShell::Theme *theme() const {
    return GetPointer<const NiriShell::Theme *>(VT_THEME);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *available_themes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_AVAILABLE_THEMES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_WORKSPACES) &&
           verifier.VerifyVector(workspaces()) &&
           verifier.VerifyVectorOfTables(workspaces()) &&
           VerifyField<int8_t>(verifier, VT_BATTERY_PERCENT, 1) &&
           VerifyOffset(verifier, VT_ACTIVE_WINDOW_TITLE) &&
           verifier.VerifyString(active_window_title()) &&
           VerifyField<int8_t>(verifier, VT_AUDIO_VOLUME, 1) &&
           VerifyField<uint8_t>(verifier, VT_AUDIO_MUTED, 1) &&
           VerifyOffset(verifier, VT_NETWORK_NAME) &&
           verifier.VerifyString(network_name()) &&
           VerifyField<uint8_t>(verifier, VT_TOGGLE_CC_SIGNAL, 1) &&
           VerifyOffset(verifier, VT_THEME) &&
           verifier.VerifyTable(theme()) &&
           VerifyOffset(verifier, VT_AVAILABLE_THEMES) &&
           verifier.VerifyVector(available_themes()) &&
           verifier.VerifyVectorOfStrings(available_themes()) &&
           verifier.EndTable();
  }
};

struct ShellStateBuilder {
  typedef ShellState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_workspaces(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<NiriShell::Workspace>>> workspaces) {
    fbb_.AddOffset(ShellState::VT_WORKSPACES, workspaces);
  }
  void add_battery_percent(int8_t battery_percent) {
    fbb_.AddElement<int8_t>(ShellState::VT_BATTERY_PERCENT, battery_percent, 0);
  }
  void add_active_window_title(::flatbuffers::Offset<::flatbuffers::String> active_window_title) {
    fbb_.AddOffset(ShellState::VT_ACTIVE_WINDOW_TITLE, active_window_title);
  }
  void add_audio_volume(int8_t audio_volume) {
    fbb_.AddElement<int8_t>(ShellState::VT_AUDIO_VOLUME, audio_volume, 0);
  }
  void add_audio_muted(bool audio_muted) {
    fbb_.AddElement<uint8_t>(ShellState::VT_AUDIO_MUTED, static_cast<uint8_t>(audio_muted), 0);
  }
  void add_network_name(::flatbuffers::Offset<::flatbuffers::String> network_name) {
    fbb_.AddOffset(ShellState::VT_NETWORK_NAME, network_name);
  }
  void add_toggle_cc_signal(uint8_t toggle_cc_signal) {
    fbb_.AddElement<uint8_t>(ShellState::VT_TOGGLE_CC_SIGNAL, toggle_cc_signal, 0);
  }
  void add_theme(::flatbuffers::Offset<NiriShell::Theme> theme) {
    fbb_.AddOffset(ShellState::VT_THEME, theme);
  }
  void add_available_themes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> available_themes) {
    fbb_.AddOffset(ShellState::VT_AVAILABLE_THEMES, available_themes);
  }
  explicit ShellStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ShellState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ShellState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ShellState> CreateShellState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<NiriShell::Workspace>>> workspaces = 0,
    int8_t battery_percent = 0,
    ::flatbuffers::Offset<::flatbuffers::String> active_window_title = 0,
    int8_t audio_volume = 0,
    bool audio_muted = false,
    ::flatbuffers::Offset<::flatbuffers::String> network_name = 0,
    uint8_t toggle_cc_signal = 0,
    ::flatbuffers::Offset<NiriShell::Theme> theme = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> available_themes = 0) {
  ShellStateBuilder builder_(_fbb);
  builder_.add_available_themes(available_themes);
  builder_.add_theme(theme);
  builder_.add_network_name(network_name);
  builder_.add_active_window_title(active_window_title);
  builder_.add_workspaces(workspaces);
  builder_.add_toggle_cc_signal(toggle_cc_signal);
  builder_.add_audio_muted(audio_muted);
  builder_.add_audio_volume(audio_volume);
  builder_.add_battery_percent(battery_percent);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ShellState> CreateShellStateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<NiriShell::Workspace>> *workspaces = nullptr,
    int8_t battery_percent = 0,
    const char *active_window_title = nullptr,
    int8_t audio_volume = 0,
    bool audio_muted = false,
    const char *network_name = nullptr,
    uint8_t toggle_cc_signal = 0,
    ::flatbuffers::Offset<NiriShell::Theme> theme = 0,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *available_themes = nullptr) {
  auto workspaces__ = workspaces ? _fbb.CreateVector<::flatbuffers::Offset<NiriShell::Workspace>>(*workspaces) : 0;
  auto active_window_title__ = active_window_title ? _fbb.CreateString(active_window_title) : 0;
  auto network_name__ = network_name ? _fbb.CreateString(network_name) : 0;
  auto available_themes__ = available_themes ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*available_themes) : 0;
  return NiriShell::CreateShellState(
      _fbb,
      workspaces__,
      battery_percent,
      active_window_title__,
      audio_volume,
      audio_muted,
      network_name__,
      toggle_cc_signal,
      theme,
      available_themes__);
}

inline const NiriShell::ShellState *GetShellState(const void *buf) {
  return ::flatbuffers::GetRoot<NiriShell::ShellState>(buf);
}

inline const NiriShell::ShellState *GetSizePrefixedShellState(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<NiriShell::ShellState>(buf);
}

template <bool B = false>
inline bool VerifyShellStateBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<NiriShell::ShellState>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedShellStateBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<NiriShell::ShellState>(nullptr);
}

inline void FinishShellStateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NiriShell::ShellState> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedShellStateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NiriShell::ShellState> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace NiriShell

#endif  // FLATBUFFERS_GENERATED_SHELLSTATE_NIRISHELL_H_
