// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SHELLSTATE_NIRISHELL_H_
#define FLATBUFFERS_GENERATED_SHELLSTATE_NIRISHELL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace NiriShell {

struct Workspace;
struct WorkspaceBuilder;

struct ShellState;
struct ShellStateBuilder;

struct Workspace FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WorkspaceBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_NAME = 6,
    VT_IS_ACTIVE = 8
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool is_active() const {
    return GetField<uint8_t>(VT_IS_ACTIVE, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID, 8) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint8_t>(verifier, VT_IS_ACTIVE, 1) &&
           verifier.EndTable();
  }
};

struct WorkspaceBuilder {
  typedef Workspace Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(Workspace::VT_ID, id, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Workspace::VT_NAME, name);
  }
  void add_is_active(bool is_active) {
    fbb_.AddElement<uint8_t>(Workspace::VT_IS_ACTIVE, static_cast<uint8_t>(is_active), 0);
  }
  explicit WorkspaceBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Workspace> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Workspace>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Workspace> CreateWorkspace(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    bool is_active = false) {
  WorkspaceBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_name(name);
  builder_.add_is_active(is_active);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Workspace> CreateWorkspaceDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    const char *name = nullptr,
    bool is_active = false) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return NiriShell::CreateWorkspace(
      _fbb,
      id,
      name__,
      is_active);
}

struct ShellState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ShellStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WORKSPACES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<NiriShell::Workspace>> *workspaces() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<NiriShell::Workspace>> *>(VT_WORKSPACES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_WORKSPACES) &&
           verifier.VerifyVector(workspaces()) &&
           verifier.VerifyVectorOfTables(workspaces()) &&
           verifier.EndTable();
  }
};

struct ShellStateBuilder {
  typedef ShellState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_workspaces(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<NiriShell::Workspace>>> workspaces) {
    fbb_.AddOffset(ShellState::VT_WORKSPACES, workspaces);
  }
  explicit ShellStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ShellState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ShellState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ShellState> CreateShellState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<NiriShell::Workspace>>> workspaces = 0) {
  ShellStateBuilder builder_(_fbb);
  builder_.add_workspaces(workspaces);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ShellState> CreateShellStateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<NiriShell::Workspace>> *workspaces = nullptr) {
  auto workspaces__ = workspaces ? _fbb.CreateVector<::flatbuffers::Offset<NiriShell::Workspace>>(*workspaces) : 0;
  return NiriShell::CreateShellState(
      _fbb,
      workspaces__);
}

inline const NiriShell::ShellState *GetShellState(const void *buf) {
  return ::flatbuffers::GetRoot<NiriShell::ShellState>(buf);
}

inline const NiriShell::ShellState *GetSizePrefixedShellState(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<NiriShell::ShellState>(buf);
}

template <bool B = false>
inline bool VerifyShellStateBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<NiriShell::ShellState>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedShellStateBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<NiriShell::ShellState>(nullptr);
}

inline void FinishShellStateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NiriShell::ShellState> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedShellStateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<NiriShell::ShellState> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace NiriShell

#endif  // FLATBUFFERS_GENERATED_SHELLSTATE_NIRISHELL_H_
